print("x:")
x = int(input())
print("*a:")
a = int(input())
print("/b:")
b = int(input())
print("+c:")
c = int(input())
print("-d:")
d = int(input())

print(x, "*", a, "/", b, "+", c, "-", d, "=", x * a / b + c - d)